### PR TITLE
Add Support for displaying item tooltip on hover

### PR DESCRIPTION
**Pull request by lantisnt**
Hi, First of all, thanks for the continuous work on this awesome framework!

I find it extremely useful to be able to display item tooltip when hovering over fields, especially in connection with using icon/execute.

This Pull Request adds:

1. New option `item` (optional, string, number, function)
2. If it's an existing ingame item it will display it on hover using global `GameTooltip` to allow for integration with AddOns modifying those.

image

### CODE REVIEW

**Review by Nevcairiel — CHANGES_REQUESTED** [review]
"item" as both a name and only supported type seems rather restrictive, and also ambigious. Maybe it should be called "tooltipHyperlink". You wouldn't be able to pass an item number this way, but its a low price to pay for the flexibility of actually passing other links.

I'm also not a fan of using GameTooltip. I understand why you want to use it, but there is also a reason why we made our own tooltip for the normal text tooltips.

**Comment by lantisnt** [comment]
So I adhered to most of the review except the `GameTooltip` because I'd like to understand why would this be negative to use it and allow other AddOns to modify it?

**Comment by funkydude** [comment]
"Integration with other addons" is not our goal. Our goal is creating and handling as much as we can outside of the scope of Blizzard code to avoid current and future taint/other issues.

What I don't understand is why you cannot just use the already existing tooltip, we give it a global name, and other addons "integrate" with it just fine via this method.

**Comment by SamMousa** [comment]
> What I don't understand is why you cannot just use the already existing tooltip, we give it a global name, and other addons "integrate" with it just fine via this method.

Actually many like pawn, tsm, inventory addons, do not in my experience.
What about making it configurable? So by default it uses aces tooltip but addon devs can optionally set it to use global?

**Comment by funkydude** [comment]
> Actually many like pawn, tsm, inventory addons, do not in my experience.

"Not our problem"

**Comment by SamMousa** [comment]
Of course not, but the goal is to help devs right?
Devs using ace face this issue and they can't fix all other addons that their users might use.
I don't agree with this vendor lock-in you are proposing, I think in this case it even hurts the framework itself.

What is the benefit of not supporting it over accepting a PR that does?

**Comment by Nevcairiel** [comment]
Staying as far away as possible from the default UI elements is a core design principle in AceGUI/AceConfigDialog (and in a more abstract sense all of Ace3). This has allowed us to keep it stable for over 15 years now without frequent breakages or unexplained interactions with other addons, or even the default UI.

We have designed it so that other addons intentionally wanting to interact with AceGUI or AceConfig can do so, but not inherit all sorts of behavior attached to a complex beast like GameTooltip. This is an intentional design goal, and not something that just happened by accident, hence being reluctant to make an exception here without a proper discussion and vetting.

It may not seem like a big deal to allow GameTooltip to be used here, however there have been numerous issues in the past with GameTooltip reacting weirdly/badly, or just simply very inconsistent behavior in combination with bigger tooltip addons - and not even those just adding a bit of information, but those that re-design the entire tooltip.

And since it was brought up, the goal is to provide a consistent and stable experience to developers, not provide every possible feature. That can mean that some features may not be as flashy as some people might want them to be, or be declined outright, but thats fine. AceConfig has a relatively narrow scope on configurable behavior, and we're not looking to extend that beyond reasonable means.

**Comment by SamMousa** [comment]
> Staying as far away as possible from the default UI elements is a core design principle in AceGUI/AceConfigDialog (and in a more abstract sense all of Ace3)

I wasn't aware this was a core principle; but if that's the case it actually makes sense.

I guess the best approach is then to implement a custom widget type via `RegisterWidgetType` and use our full frame control to render something the way we want it without altering core framework code?

**Comment by Nevcairiel** [comment]
Custom widget overrides are definitely a good option if you want full control over the behavior or design of a certain element. I use it myself in various situations.

**Comment by lantisnt** [comment]
I did use custom widgets when using AceGUI but Is there a way to use one in conjunction wth AceConfigDialog?

**Comment by Nevcairiel** [comment]
You can specify the control to use with the dialogControl option table command. See also https://www.wowace.com/projects/ace3/pages/ace-config-3-0-options-tables#title-5

**Review by Nevcairiel — APPROVED** [review]
The changes look good now, quite a lot simpler this way and still quite helpful for many addons I'm sure.

I'll likely merge this after the 10.0 release rush, just to be safe.
Note for merging: version bump is still needed.

**Comment by funkydude** [comment]
Tiny nitpick:
I'd like to see `local tooltipHyperlink = GetOptionsMemberValue("tooltipHyperlink", opt, options, path, appName)` moved down above `if tooltipHyperlink then`

e.g.
```
tooltip:SetOwner(widget.frame, "ANCHOR_TOPRIGHT")

local tooltipHyperlink = GetOptionsMemberValue("tooltipHyperlink", opt, options, path, appName)
if tooltipHyperlink then
```

This keeps them separate and keeps it closer to the other `GetOptionsMemberValue` calls.

**Comment by lantisnt** [comment]
Updated per request and bumped the version

**Review by funkydude — APPROVED** [review]

**Comment by Nevcairiel** [comment]
Merged as 6d99e3fa8e8927f8a37bb0c1211f86951b81655a

**Pull request closed without merging**
